### ISSUE TITLE
Value error on truth values when running fixed number connectors

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/SpiNNFrontEndCommon#288]
Running e.g. https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_fixed_number_connectors/test_fixed_number_pre_connector.py gives the following:

===============================================2018-02-27 11:27:01 ERROR: Error when calling pacman.operations.partition_algorithms.partition_and_place_partitioner.PartitionAndPlacePartitioner.__call__ with inputs {'machine': [Machine: max_x=1, max_y=1, n_chips=4], 'graph': <pacman.model.graphs.application.application_graph.ApplicationGraph object at 0x7f48bd676848>, 'preallocated_resources': <pacman.model.resources.pre_allocated_resource_container.PreAllocatedResourceContainer object at 0x7f48babee730>}
Traceback (most recent call last):
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/p8_integration_tests/test_fixed_number_connectors/test_fixed_number_pre_connector.py", line 197, in <module>
    stim_spikes, spklist_exc, spklist_inh = do_run(plot=True)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/p8_integration_tests/test_fixed_number_connectors/test_fixed_number_pre_connector.py", line 141, in do_run
    p.run(sim_duration)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/__init__.py", line 528, in run
    return __pynn_run(simtime, callbacks=callbacks)
  File "/localhome/mbbssag3/Downloads/PyNN/PyNN-0.9.1/PyNN9/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/localhome/mbbssag3/Downloads/PyNN/PyNN-0.9.1/PyNN9/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/spinnaker.py", line 127, in run_until
    self._run(tstop - self.t)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/spinnaker.py", line 174, in _run
    AbstractSpiNNakerCommon.run(self, duration_ms)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 315, in run
    AbstractSpinnakerBase._run(self, run_time)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 944, in _run
    self._do_mapping(run_time, n_machine_time_steps, total_run_time)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1690, in _do_mapping
    optional_algorithms)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1192, in _run_algorithms
    executor.execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 623, in execute_mapping
    self._execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 639, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 48, in call
    results = self.call_python(method_inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 59, in call_python
    return method(**inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 86, in __call__
    graph, progress, vertex_groups)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 139, in _partition_vertex
    machine_graph, graph, graph_mapper, resource_tracker, progress)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 193, in _partition_by_atoms
    vertex))
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py", line 266, in create_machine_vertex
    reserve_reverse_ip_tag=self._reserve_reverse_ip_tag)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/injection_decorator.py", line 22, in new_init
    orig_init(self, *args, **kwargs)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 186, in __init__
    buffer_notification_tag, board_address))
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 227, in _install_send_buffer
    if (send_buffer_times and
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by rowleya** [comment]
Fixed by above merge.
